version: '3.8'
services:
  product-engine-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=product-engine-db
      - POSTGRES_USER=product-engine
      - POSTGRES_PASSWORD=product-engine
    ports:
      - '5432:5432'
    volumes:
      - product-engine-db:/var/lib/postgresql/data
  origination-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=origination-db
      - POSTGRES_USER=origination
      - POSTGRES_PASSWORD=origination
    ports:
      - '5432:5432'
    volumes:
      - origination-db:/var/lib/postgresql/data

volumes:
  product-engine-db:
    driver: local
  origination-db:
    driver: local