grpc:
  port: 9095
  enable-reflection: true

spring:
  liquibase:
    enabled: true
    changeLog: classpath:/db/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/product-engine-db
    user: product-engine
    password: product-engine
  datasource:
    url: jdbc:postgresql://localhost:5432/product-engine-db
    username: product-engine
    password: product-engine
  kafka:
    bootstrap-servers: localhost:9092

exporter:
  agreement:
    topic: "pe.agreement.v1"
    timeout: 10000