server:
  port: 8087

grpc:
  port: 9097
  enable-reflection: true

pg:
  client:
    mp:
      rest:
        url: "localhost:8088/mp/payment"
    pe:
      grpc:
        host: localhost
        port: 9095